services:
  db:
    image: mongo:8.0.9
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
      MONGO_INITDB_DATABASE: pinder-dev
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - pinder-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - pinder-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - pinder-net

volumes:
  mongodb-data:
    name: mongodb-data

networks:
  pinder-net:
    driver: bridge
